[DRAFT] Add Portis support
rsksmart/rif-identity-manager pull request #81
Opened 2021-05-14 11:08 UTC by jessgusclark

Pending release of the next version of rLogin.

- Adds Portis as a web3 provider. 
- Also, when the provider is not metamask, the DataVault content will be decrypted onLoad since the `SignerEncryptionManager` does not need interaction from the user's wallet to decrypt content.

2021-05-20 15:39 UTC, ilanolkies commented
Requires https://github.com/rsksmart/rLogin/pull/89

2021-05-24 14:15 UTC, jessgusclark commented
Opening up for review for QA testing. Redeploying since #84 overwrote the deployment.

2021-06-10 10:24 UTC, jessgusclark commented
After talking with @miltonwg , I have updated the description in the Readme to indicate that the wrapper will add the `gasPrice` when sending `request`. However, the developer will need to add a `gasPrice` if they use `send` or `sendAsync`.

I also bumped the `gasPrice` by 1% as requested by @ilanolkies . This PR is ready to go, below is the status of the App's support of Portis. I checked the Apps below using `yarn link` as a few extra commits have been added.

- [x] VC Issuer - Worked fine as it does not have any transactions, only signatures. Portis support is already merged into main. [deployed to production here](https://email-verifier.identity.rifos.org/)
- [x] RIF Id Manager - As Ken found, the identity section does not work. After talking with Milton, it was decided to show a message letting the user know they can't update their data. [A PR is ready to be merged here](https://github.com/rsksmart/rif-identity-manager/pull/81). 
- [x] RNS Manager React - Works locally, however, the published rLogin package 1.0.7-beta.1 does not support rawTransactions, so [this PR](https://github.com/rnsdomains/rns-manager-react/pull/417) will need to wait until the next version is released then updated.

2021-06-14 14:42 UTC, ilanolkies requested changes
Let's use `v1.0.8`

2021-06-14 15:34 UTC, ilanolkies approved these changes

2021-06-14 15:34 UTC, merged